/**
 * @file test_bignum_isqrt_mt.c
 * @brief Multithreaded independent-call test for bignum_isqrt.
 * @version 1.0.0
 * @date 2026-08-22
 * @details Each thread owns all input/output records; the test verifies the
 * documented no-global-state thread-safety guarantee against an integer oracle.
 */
#include "bignum_isqrt.h"
#include <assert.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

/**
 * @brief Stores one worker's independent test state.
 * @details The argument remains valid until pthread_join; no field is shared
 * concurrently except the owning worker's failure flag.
 */
struct worker_arg {
    unsigned id; /**< Stable worker id used to derive a deterministic seed. */
    int failed; /**< Set to one by the worker after the first oracle mismatch. */
};

/**
 * @brief Computes the independent uint64_t floor-square-root oracle.
 * @param[in] v Radicand generated by the worker-local PRNG.
 * @return Exact floor(sqrt(v)) using overflow-safe __uint128_t multiplication.
 */
static uint64_t root64(uint64_t v) { uint64_t lo=0,hi=UINT64_C(0xffffffff),best=0; while(lo<=hi){uint64_t m=lo+((hi-lo)>>1);if(m==0||(__uint128_t)m*m<=v){best=m;lo=m+1;}else hi=m-1;}return best; }

/** @brief Advances a worker-local deterministic xorshift state. */
static uint64_t next_random(uint64_t *s) { *s ^= *s << 7; *s ^= *s >> 9; *s ^= *s << 8; return *s; }

/**
 * @brief Executes 2,000 independent calls for one thread.
 * @details The seed is `0x123456789abcdef0 + worker_id`; each call checks named
 * SUCCESS, exact oracle value and normalized length. The first mismatch marks
 * the worker failure flag and terminates that worker.
 * @param[in,out] opaque Borrowed worker_arg owned by the joining main thread.
 * @return Always NULL as required by the pthread start routine.
 */
static void *worker(void *opaque)
{
    struct worker_arg *arg = opaque; uint64_t s = UINT64_C(0x123456789abcdef0) + arg->id;
    for (size_t i=0; i<2000; ++i) { bignum_t x,r; uint64_t v=next_random(&s), expected=root64(v); memset(&x,0,sizeof x); x.len=v?1:0; x.words[0]=v; memset(&r,0xa5,sizeof r); if(bignum_isqrt(&r,&x)!=BIGNUM_ISQRT_SUCCESS || r.len!=(expected?1U:0U) || (r.len && r.words[0]!=expected)){arg->failed=1;return NULL;} }
    return NULL;
}
/**
 * @brief Starts eight workers and verifies the documented thread-safety contract.
 * @return Zero only after every worker has joined without an oracle mismatch.
 */
int main(void)
{
    enum { THREADS = 8 }; pthread_t threads[THREADS]; struct worker_arg args[THREADS];
    puts("--- Starting multithreaded bignum_isqrt tests ---");
    for (unsigned i=0;i<THREADS;++i){args[i]=(struct worker_arg){i,0};assert(pthread_create(&threads[i],NULL,worker,&args[i])==0);}
    for (unsigned i=0;i<THREADS;++i){assert(pthread_join(threads[i],NULL)==0);assert(args[i].failed==0);}
    puts("--- Multithreaded bignum_isqrt test passed ---"); return 0;
}
